site_name: Revfore Accelerate Docs
site_description: Documentation for Revfore Accelerate
site_url: https://docs.revfore.com/revfore-accelerate/
repo_url: https://github.com/revfore/revfore-accelerate-docs
repo_name: revfore-accelerate-docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Setup & Installation: setup/setup.md
  - Core Concepts:
      - Relational Tables: concepts/tables.md
      - Relational Models: concepts/models.md
      - Relational Views: concepts/views.md
      - Metadata-Driven UI: concepts/metadataDrivenUI.md
  - Application Groups:
      - Config:
          - Overview: appGroups/config/index.md
          - Manage License Keys: appGroups/config/manage-license-key.md   
          - Setup & Upgrade: appGroups/config/setup-upgrade.md
          - Create Instance: appGroups/config/createInstance.md          
          - Uninstall: appGroups/config/uninstall.md
          - Run Maintenance Scripts: appGroups/config/run-maintenance-scripts.md
          - Other: appGroups/config/other.md  
      - Admin:
          - Overview: appGroups/admin/index.md
          - Relational Tables:
              - Overview: appGroups/admin/relationalTables/index.md
              - Tables: appGroups/admin/relationalTables/tables.md
              - Columns: appGroups/admin/relationalTables/columns.md
              - Indexes: appGroups/admin/relationalTables/indexes.md
              - Relationships: appGroups/admin/relationalTables/relationships.md
          - Relational Models:
              - Overview: appGroups/admin/relationalModels/index.md
              - Models: appGroups/admin/relationalModels/models.md              
              - Sources: appGroups/admin/relationalModels/sources.md
              - Columns: appGroups/admin/relationalModels/columns.md
              - Relationships: appGroups/admin/relationalModels/relationships.md
          - Relational Views:
              - Overview: appGroups/admin/relationalViews/index.md
              - Views: appGroups/admin/relationalViews/views.md              
              - Columns: appGroups/admin/relationalViews/columns.md
              - Actions: appGroups/admin/relationalViews/actions.md
              - Filters: appGroups/admin/relationalViews/filters.md
          - Lookups: appGroups/admin/lookups.md
          - Forms: appGroups/admin/forms.md
      - Home: appGroups/home/index.md
      - Help: appGroups/help/index.md
  - Integrations: 
      - Genesis Page:
          - Overview: integrations/genesis/index.md
          - Content Item Layouts: integrations/genesis/contentItemLayouts.md
          - Content Sub Item Settings: integrations/genesis/contentSubItemSettings.md
      - Custom Page:
          - Overview: integrations/customPage/index.md
          - Content Item Layouts: integrations/customPage/contentItemLayouts.md
          - Content Sub Item Settings: integrations/customPage/contentSubItemSettings.md     
      - Partner Solution:          
          - Overview: integrations/partnerSolution/index.md      
      - Excel:
          - Overview: integrations/excel/index.md
      - REST APIs:
          - Overview: integrations/restAPIs/index.md

plugins:
  - search
  - mike:
      deploy_prefix: revfore-accelerate
      alias_type: copy

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

copyright: Copyright © 2026 Revfore
