site_name: Revfore Accelerate Docs
site_description: Documentation for Revfore Accelerate
site_url: https://docs.revfore.com/revfore-accelerate/
repo_url: https://github.com/revfore/revfore-accelerate-docs
repo_name: revfore-accelerate-docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Setup & Installation: setup/setup.md
  - Core Concepts:
      - Relational Tables: concepts/tables.md
      - Relational Models: concepts/models.md
      - Relational Views: concepts/views.md
  - Application Groups:
      - Config:
          - Overview: appGroups/config/index.md
          - Manage License Keys: appGroups/config/manage-license-key.md   
          - Setup & Upgrade: appGroups/config/setup-upgrade.md
          - Uninstall: appGroups/config/uninstall.md
          - Run Maintenance Scripts: appGroups/config/run-maintenance-scripts.md
          - Other: appGroups/config/other.md  
      - Admin:
          - Overview: appGroups/admin/index.md
          - Relational Tables: appGroups/admin/relational-tables.md
          - Relational Models: appGroups/admin/relational-models.md
          - Relational Views: appGroups/admin/relational-views.md
          - Lookups: appGroups/admin/lookups.md
          - Forms: appGroups/admin/forms.md
      - Home: appGroups/home/index.md
      - Help: appGroups/help/index.md

plugins:
  - search
  - mike:
      deploy_prefix: revfore-accelerate
      alias_type: copy

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

copyright: Copyright © 2026 Revfore
